require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InformersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Informer. As you add validations to Informer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InformersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all informers as @informers" do
      informer = Informer.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:informers)).to eq([informer])
    end
  end

  describe "GET #show" do
    it "assigns the requested informer as @informer" do
      informer = Informer.create! valid_attributes
      get :show, {:id => informer.to_param}, valid_session
      expect(assigns(:informer)).to eq(informer)
    end
  end

  describe "GET #new" do
    it "assigns a new informer as @informer" do
      get :new, {}, valid_session
      expect(assigns(:informer)).to be_a_new(Informer)
    end
  end

  describe "GET #edit" do
    it "assigns the requested informer as @informer" do
      informer = Informer.create! valid_attributes
      get :edit, {:id => informer.to_param}, valid_session
      expect(assigns(:informer)).to eq(informer)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Informer" do
        expect {
          post :create, {:informer => valid_attributes}, valid_session
        }.to change(Informer, :count).by(1)
      end

      it "assigns a newly created informer as @informer" do
        post :create, {:informer => valid_attributes}, valid_session
        expect(assigns(:informer)).to be_a(Informer)
        expect(assigns(:informer)).to be_persisted
      end

      it "redirects to the created informer" do
        post :create, {:informer => valid_attributes}, valid_session
        expect(response).to redirect_to(Informer.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved informer as @informer" do
        post :create, {:informer => invalid_attributes}, valid_session
        expect(assigns(:informer)).to be_a_new(Informer)
      end

      it "re-renders the 'new' template" do
        post :create, {:informer => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested informer" do
        informer = Informer.create! valid_attributes
        put :update, {:id => informer.to_param, :informer => new_attributes}, valid_session
        informer.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested informer as @informer" do
        informer = Informer.create! valid_attributes
        put :update, {:id => informer.to_param, :informer => valid_attributes}, valid_session
        expect(assigns(:informer)).to eq(informer)
      end

      it "redirects to the informer" do
        informer = Informer.create! valid_attributes
        put :update, {:id => informer.to_param, :informer => valid_attributes}, valid_session
        expect(response).to redirect_to(informer)
      end
    end

    context "with invalid params" do
      it "assigns the informer as @informer" do
        informer = Informer.create! valid_attributes
        put :update, {:id => informer.to_param, :informer => invalid_attributes}, valid_session
        expect(assigns(:informer)).to eq(informer)
      end

      it "re-renders the 'edit' template" do
        informer = Informer.create! valid_attributes
        put :update, {:id => informer.to_param, :informer => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested informer" do
      informer = Informer.create! valid_attributes
      expect {
        delete :destroy, {:id => informer.to_param}, valid_session
      }.to change(Informer, :count).by(-1)
    end

    it "redirects to the informers list" do
      informer = Informer.create! valid_attributes
      delete :destroy, {:id => informer.to_param}, valid_session
      expect(response).to redirect_to(informers_url)
    end
  end

end
